### ISSUE TITLE
Create Database Classes

### ISSUE THREAD

**Issue by EagleEye25** [EagleEye25/uniPark-BackEnd#24]
# Create Database classes
We need to create database classes, to allow the app to comunicate with the database
Please ensure that classes are saved within the classes folder, and that each created class is placed
within a folder which is named according to the class name, to keep files, code neat
(Read, Update, Add)

**Comment by wihanduplessis** [comment]
Created Model and Viewmodel classes. https://github.com/EagleEye25/uniPark-BackEnd/pull/27

**Comment by Mauricegdg** [comment]
Creating DBAccess Class now to complete basic functionality. I'm going to make changes to a few SP's along the way but with load the changes to Drive Under my name when done.
